"""sitio URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
#from django.conf.urls import url, patterns
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
#Procesos
    #url(r'^$',indexView.as_view(),name='index'),
    url(r'^$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name='login'),
    url(r'^cerrar/$', 'django.contrib.auth.views.logout_then_login', name='logout'),

    #url(r'^resumen_general$',login_required(indexView.as_view()),name='index'),
    url(r'^informes_procesos/$', login_required(verResumenGeneral), name='index'),
    
    url(r'^informes_relacion_1/$', login_required(verResumenRelacion), name='index2'),
    url(r'^informes_relacion_2/$', login_required(verResumenRelacion2), name='index22'),
    
    url(r'^informes_resolucion_1/$', login_required(verResumenResolucion), name='index3'),
    url(r'^informes_resolucion_2/$', login_required(verResumenResolucion2), name='index33'),
    
    url(r'^informes_control_1/$', login_required(verResumenControl), name='index4'),
    url(r'^informes_control_2/$', login_required(verResumenControl2), name='index44'),
    
    url(r'^configuracion/$', login_required(Configuracion_View.as_view()),name='configuracion'),
    url(r'^cambios/$', login_required(Cambios_View.as_view()),name='cambios'),
    url(r'^peticiones/$', login_required(Peticiones_View.as_view()),name='peticiones'),
    url(r'^problemas/$', login_required(Problemas_View.as_view()),name='problemas'),
    url(r'^proveedores/$', login_required(Proveedores_View.as_view()),name='proveedores'),
    url(r'^clientes/$', login_required(Clientes_View.as_view()),name='clientes'),
    url(r'^seguridad/$', login_required(Seguridad_View.as_view()),name='seguridad'),
#Configuracion
    url(r'^nueva_Clasificacion/$', login_required(newClasificacion) ,name='nuevo_clasificacion'),
    url(r'^mostrar_Clasificacion/$', login_required(verClasificacion) ,name='mostrar_clasificacion'),
    url(r'^editar_Clasificacion/(?P<id>\d+)$', login_required(editarClasificacion) ,name='editar_clasificacion'),
    url(r'^eliminar_Clasificacion/(?P<id>\d+)$', login_required(eliminarClasificacion), name='eliminar_clasificacion'),
    url(r'^nuevo_EC/$', login_required(newEC), name='nuevo_ec'),
    url(r'^mostrar_EC/$', login_required(verEC), name='mostrar_ec'),
    url(r'^editar_EC/(?P<id>\d+)$', login_required(editarEC), name='editar_ec'),
    url(r'^eliminar_EC/(?P<id>\d+)$', login_required(eliminarEC), name='eliminar_ec'),
    url(r'^nueva_Organizacion/$', login_required(newOrganizacion), name='nuevo_organizacion'),
    url(r'^mostrar_Organizacion/$', login_required(verOrganizacion), name='mostrar_organizacion'),
    url(r'^editar_Organizacion/(?P<id>\d+)$', login_required(editarOrganizacion), name='editar_organizacion'),
    url(r'^eliminar_Organizacion/(?P<id>\d+)$', login_required(eliminarOrganizacion), name='eliminar_organizacion'),
    url(r'^nueva_Localidad/$', login_required(newLocalidad), name='nuevo_localidad'),
    url(r'^mostrar_Localidad/$', login_required(verLocalidad), name='mostrar_localidad'),
    url(r'^editar_Localidad/(?P<id>\d+)$', login_required(editarLocalidad), name='editar_localidad'),
    url(r'^eliminar_Localidad/(?P<id>\d+)$', login_required(eliminarLocalidad), name='eliminar_localidad'),
    url(r'^nuevo_Grupo/$', login_required(newGrupo), name='nuevo_grupo'),
    url(r'^mostrar_Grupo/$', login_required(verGrupo), name='mostrar_grupo'),
    url(r'^editar_Grupo/(?P<id>\d+)$', login_required(editarGrupo), name='editar_grupo'),
    url(r'^eliminar_Grupo/(?P<id>\d+)$', login_required(eliminarGrupo), name='eliminar_grupo'),
    url(r'^nuevo_Dato_General/$', login_required(newGeneral), name='nuevo_general'),
    url(r'^mostrar_Dato_General/$', login_required(verGeneral), name='mostrar_general'),
    url(r'^editar_Dato_General/(?P<id>\d+)$', login_required(editarGeneral), name='editar_general'),
    url(r'^eliminar_Dato_General/(?P<id>\d+)$', login_required(eliminarGeneral), name='eliminar_general'),
    url(r'^nueva_Marca/$', login_required(newMarca), name='nueva_marca'),
    url(r'^mostrar_Marca/$', login_required(verMarca), name='mostrar_marca'),
    url(r'^editar_Marca/(?P<id>\d+)$', login_required(editarMarca), name='editar_marca'),
    url(r'^eliminar_Marca/(?P<id>\d+)$', login_required(eliminarMarca), name='eliminar_marca'),
    url(r'^nuevo_Modelo/$', login_required(newModelo), name='nuevo_modelo'),
    url(r'^mostrar_Modelo/$', login_required(verModelo), name='mostrar_modelo'),
    url(r'^editar_Modelo/(?P<id>\d+)$', login_required(editarModelo), name='editar_modelo'),
    url(r'^eliminar_Modelo/(?P<id>\d+)$', login_required(eliminarModelo), name='eliminar_modelo'),
    url(r'^nueva_Red/$', login_required(newRed), name='nuevo_red'),
    url(r'^mostrar_Red/$', login_required(verRed), name='mostrar_red'),
    url(r'^editar_Red/(?P<id>\d+)$', login_required(editarRed), name='editar_red'),
    url(r'^eliminar_Red/(?P<id>\d+)$', login_required(eliminarRed), name='eliminar_red'),
    url(r'^nuevo_Software/$', login_required(newSoftware), name='nuevo_software'),
    url(r'^mostrar_Software/$', login_required(verSoftware), name='mostrar_software'),
    url(r'^editar_Software/(?P<id>\d+)$', login_required(editarSoftware), name='editar_software'),
    url(r'^eliminar_Software/(?P<id>\d+)$', login_required(eliminarSoftware), name='eliminar_software'), 
    url(r'^nueva_Version/$', login_required(newVersion), name='nuevo_version'),
    url(r'^mostrar_Version/$', login_required(verVersion), name='mostrar_version'),
    url(r'^editar_Version/(?P<id>\d+)$', login_required(editarVersion), name='editar_version'),
    url(r'^eliminar_Version/(?P<id>\d+)$', login_required(eliminarVersion), name='eliminar_version'),
    url(r'^nueva_Impresora/$', login_required(newImpresora), name='nuevo_impresora'),
    url(r'^mostrar_Impresora/$', login_required(verImpresora), name='mostrar_impresora'),
    url(r'^editar_Impresora/(?P<id>\d+)$', login_required(editarImpresora), name='editar_impresora'),
    url(r'^eliminar_Impresora/(?P<id>\d+)$', login_required(eliminarImpresora), name='eliminar_impresora'), 
    url(r'^nueva_Granja/$', login_required(newGranja), name='nuevo_granja'),
    url(r'^mostrar_Granja/$', login_required(verGranja), name='mostrar_granja'),
    url(r'^editar_Granja/(?P<id>\d+)$', login_required(editarGranja), name='editar_granja'),
    url(r'^eliminar_Granja/(?P<id>\d+)$', login_required(eliminarGranja), name='eliminar_granja'), 
    url(r'^nueva_Licencia/$', login_required(newLicencia), name='nuevo_licencia'),
    url(r'^mostrar_Licencia/$', login_required(verLicencia), name='mostrar_licencia'),
    url(r'^editar_Licencia/(?P<id>\d+)$', login_required(editarLicencia), name='editar_licencia'),
    url(r'^eliminar_Licencia/(?P<id>\d+)$', login_required(eliminarLicencia), name='eliminar_licencia'), 
    url(r'^nueva_Maquina_virtual/$', login_required(newMaquina), name='nuevo_maquina'),
    url(r'^mostrar_Maquina_virtual/$', login_required(verMaquina), name='mostrar_maquina'),
    url(r'^editar_Maquina_virtual/(?P<id>\d+)$', login_required(editarMaquina), name='editar_maquina'),
    url(r'^eliminar_Maquina_virtual/(?P<id>\d+)$', login_required(eliminarMaquina), name='eliminar_maquina'), 
    url(r'^nueva_Vlan/$', login_required(newVlan), name='nuevo_vlan'),
    url(r'^mostrar_Vlan/$', login_required(verVlan), name='mostrar_vlan'),
    url(r'^editar_Vlan/(?P<id>\d+)$', login_required(editarVlan), name='editar_vlan'),
    url(r'^eliminar_Vlan/(?P<id>\d+)$', login_required(eliminarVlan), name='eliminar_vlan'),
    url(r'^nuevo_Contacto/$', login_required(newContacto), name='nuevo_contacto'),
    url(r'^mostrar_Contacto/$', login_required(verContacto), name='mostrar_contacto'),
    url(r'^editar_Contacto/(?P<id>\d+)$', login_required(editarContacto), name='editar_contacto'),
    url(r'^eliminar_Contacto/(?P<id>\d+)$', login_required(eliminarContacto), name='eliminar_contacto'),
    url(r'^nueva_PC/$', login_required(newPC), name='nuevo_pc'),
    url(r'^mostrar_PC/$', login_required(verPC), name='mostrar_pc'),
    url(r'^editar_PC/(?P<id>\d+)$', login_required(editarPC), name='editar_pc'),
    url(r'^eliminar_PC/(?P<id>\d+)$', login_required(eliminarPC), name='eliminar_pc'), 
    url(r'^nueva_Instalacion/$', login_required(newInstalacion), name='nuevo_instalacion'),
    url(r'^mostrar_Instalacion/$', login_required(verInstalacion), name='mostrar_instalacion'),
    url(r'^editar_Instalacion/(?P<id>\d+)$', login_required(editarInstalacion), name='editar_instalacion'),
    url(r'^eliminar_Instalacion/(?P<id>\d+)$', login_required(eliminarInstalacion), name='eliminar_instalacion'), 
    url(r'^nuevo_Rack/$', login_required(newRack), name='nuevo_rack'),
    url(r'^mostrar_Rack/$', login_required(verRack), name='mostrar_rack'),
    url(r'^editar_Rack/(?P<id>\d+)$', login_required(editarRack), name='editar_rack'),
    url(r'^eliminar_Rack/(?P<id>\d+)$', login_required(eliminarRack), name='eliminar_rack'), 
    url(r'^nuevo_Servidor/$', login_required(newServidor), name='nuevo_servidor'),
    url(r'^mostrar_Servidor/$', login_required(verServidor), name='mostrar_servidor'),
    url(r'^editar_Servidor/(?P<id>\d+)$', login_required(editarServidor), name='editar_servidor'),
    url(r'^eliminar_Servidor/(?P<id>\d+)$', login_required(eliminarServidor), name='eliminar_servidor'),                  
    url(r'^nuevo_Hypervisor/$', login_required(newHypervisor), name='nuevo_hypervisor'),
    url(r'^mostrar_Hypervisor/$', login_required(verHypervisor), name='mostrar_hypervisor'),
    url(r'^editar_Hypervisor/(?P<id>\d+)$', login_required(editarHypervisor), name='editar_hypervisor'),
    url(r'^eliminar_Hypervisor/(?P<id>\d+)$', login_required(eliminarHypervisor), name='eliminar_hypervisor'),                  
    url(r'^nuevo_Telefono/$', login_required(newTelefono), name='nuevo_telefono'),
    url(r'^mostrar_Telefono/$', login_required(verTelefono), name='mostrar_telefono'),
    url(r'^editar_Telefono/(?P<id>\d+)$', login_required(editarTelefono), name='editar_telefono'),
    url(r'^eliminar_Telefono/(?P<id>\d+)$', login_required(eliminarTelefono), name='eliminar_telefono'),                  
    url(r'^nuevo_Dispositivo_red/$', login_required(newDispositivo), name='nuevo_dispositivo'),
    url(r'^mostrar_Dispositivo_red/$', login_required(verDispositivo), name='mostrar_dispositivo'),
    url(r'^editar_Dispositivo_red/(?P<id>\d+)$', login_required(editarDispositivo), name='editar_dispositivo'),
    url(r'^eliminar_Dispositivo_red/(?P<id>\d+)$', login_required(eliminarDispositivo), name='eliminar_dispositivo'),                  
    url(r'^nueva_Interfaz_red/$', login_required(newInterfaz), name='nuevo_interfaz'),
    url(r'^mostrar_Interfaz_red/$', login_required(verInterfaz), name='mostrar_interfaz'),
    url(r'^editar_Interfaz_red/(?P<id>\d+)$', login_required(editarInterfaz), name='editar_interfaz'),
    url(r'^eliminar_Interfaz_red/(?P<id>\d+)$', login_required(eliminarInterfaz), name='eliminar_interfaz'),                  
#Cambios                      
    url(r'^nueva_Solicitud_cambio/$', login_required(newCambio), name='nuevo_cambio'),
    url(r'^mostrar_Solicitud_cambio/$', login_required(verCambio), name='mostrar_cambio'),
    url(r'^editar_Solicitud_cambio/(?P<id>\d+)$', login_required(editarCambio), name='editar_cambio'),
    url(r'^eliminar_Solicitud_cambio/(?P<id>\d+)$', login_required(eliminarCambio), name='eliminar_cambio'),
    url(r'^nuevo_Exclusivo_cambio/$', login_required(newExclusivo), name='nuevo_exclusivo'),
    url(r'^mostrar_Exclusivo_cambio/$', login_required(verExclusivo), name='mostrar_exclusivo'),
    url(r'^editar_Exclusivo_cambio/(?P<id>\d+)$', login_required(editarExclusivo), name='editar_exclusivo'),
    url(r'^eliminar_Exclusivo_cambio/(?P<id>\d+)$', login_required(eliminarExclusivo), name='eliminar_exclusivo'),  
    url(r'^nueva_Reunion/$', login_required(newReunion), name='nuevo_reunion'),
    url(r'^mostrar_Reunion/$', login_required(verReunion), name='mostrar_reunion'),
    url(r'^editar_Reunion/(?P<id>\d+)$', login_required(editarReunion), name='editar_reunion'),
    url(r'^eliminar_Reunion/(?P<id>\d+)$', login_required(eliminarReunion), name='eliminar_reunion'),
    url(r'^nueva_Asistencia_reunion/$', login_required(newAsistencia), name='nuevo_asistencia'),
    url(r'^mostrar_Asistencia_reunion/$', login_required(verAsistencia), name='mostrar_asistencia'),
    url(r'^editar_Asistencia_reunion/(?P<id>\d+)$', login_required(editarAsistencia), name='editar_asistencia'),
    url(r'^eliminar_Asistencia_reunion/(?P<id>\d+)$', login_required(eliminarAsistencia), name='eliminar_asistencia'), 
    url(r'^nueva_Planificacion_cambio/$', login_required(newPlanificacionCambio), name='nuevo_planificacion_cambio'),
    url(r'^mostrar_Planificacion_cambio/$', login_required(verPlanificacionCambio), name='mostrar_planificacion_cambio'),
    url(r'^editar_Planificacion_cambio/(?P<id>\d+)$', login_required(editarPlanificacionCambio), name='editar_planificacion_cambio'),
    url(r'^eliminar_Planificacion_cambio/(?P<id>\d+)$', login_required(eliminarPlanificacionCambio), name='eliminar_planificacion_cambio'),           
    url(r'^nuevo_Responsable_cambio/$', login_required(newResponsableCambio), name='nuevo_responsable_cambio'),
    url(r'^mostrar_Responsable_cambio/$', login_required(verResponsableCambio), name='mostrar_responsable_cambio'),
    url(r'^editar_Responsable_cambio/(?P<id>\d+)$', login_required(editarResponsableCambio), name='editar_responsable_cambio'),
    url(r'^eliminar_Responsable_cambio/(?P<id>\d+)$', login_required(eliminarResponsableCambio), name='eliminar_responsable_cambio'),     
    url(r'^nuevo_Seguimiento_responsable/$', login_required(newSeguimientoCambio), name='nuevo_seguimiento_cambio'),
    url(r'^mostrar_Seguimiento_responsable/$', login_required(verSeguimientoCambio), name='mostrar_seguimiento_cambio'),
    url(r'^editar_Seguimiento_responsable/(?P<id>\d+)$', login_required(editarSeguimientoCambio), name='editar_seguimiento_cambio'),
    url(r'^eliminar_Seguimiento_responsable/(?P<id>\d+)$', login_required(eliminarSeguimientoCambio), name='eliminar_seguimiento_cambio'),
    url(r'^nueva_Verificacion_cambio/$', login_required(newVerificacionCambio), name='nuevo_verificacion_cambio'),
    url(r'^mostrar_Verificacion_cambio/$', login_required(verVerificacionCambio), name='mostrar_verificacion_cambio'),
    url(r'^editar_Verificacion_cambio/(?P<id>\d+)$', login_required(editarVerificacionCambio), name='editar_verificacion_cambio'),
    url(r'^eliminar_Verificacion_cambio/(?P<id>\d+)$', login_required(eliminarVerificacionCambio), name='eliminar_verificacion_cambio'),   
#Peticiones
    url(r'^nuevo_Servicio/$', login_required(newServicio), name='nuevo_servicio'),
    url(r'^mostrar_Servicio/$', login_required(verServicio), name='mostrar_servicio'),
    url(r'^editar_Servicio/(?P<id>\d+)$', login_required(editarServicio), name='editar_servicio'),
    url(r'^eliminar_Servicio/(?P<id>\d+)$', eliminarServicio, name='eliminar_servicio'),   
    url(r'^nueva_Subcategoria/$', login_required(newSubcategoria), name='nuevo_subcategoria'),
    url(r'^mostrar_Subcategoria/$', login_required(verSubcategoria), name='mostrar_subcategoria'),
    url(r'^editar_Subcategoria/(?P<id>\d+)$', login_required(editarSubcategoria), name='editar_subcategoria'),
    url(r'^eliminar_Subcategoria/(?P<id>\d+)$', login_required(eliminarSubcategoria), name='eliminar_subcategoria'),   
    url(r'^nuevo_Producto/$', login_required(newProducto), name='nuevo_producto'),
    url(r'^mostrar_Producto/$', login_required(verProducto), name='mostrar_producto'),
    url(r'^editar_Producto/(?P<id>\d+)$', login_required(editarProducto), name='editar_producto'),
    url(r'^eliminar_Producto/(?P<id>\d+)$', login_required(eliminarProducto), name='eliminar_producto'),
    url(r'^nueva_Peticion/$', login_required(newPeticion), name='nuevo_peticion'),
    #url(r'^nueva_Peticion/$', render_peticion, name='nuevo_peticion'),
    url(r'^mostrar_Peticion/$', login_required(verPeticion), name='mostrar_peticion'),
    url(r'^editar_Peticion/(?P<id>\d+)$', login_required(editarPeticion), name='editar_peticion'),
    url(r'^eliminar_Peticion/(?P<id>\d+)$', login_required(eliminarPeticion), name='eliminar_peticion'),
    
    url(r'^nueva_Asignacion_producto/$', login_required(newAsignacionProducto), name='nuevo_asignacion_producto'),
    url(r'^mostrar_Asignacion_producto/$', login_required(verAsignacionProducto), name='mostrar_asignacion_producto'),
    url(r'^editar_Asignacion_producto/(?P<id>\d+)$', login_required(editarAsignacionProducto), name='editar_asignacion_producto'),
    url(r'^eliminar_Asignacion_producto/(?P<id>\d+)$', login_required(eliminarAsignacionProducto), name='eliminar_asignacion_producto'),
    url(r'^nueva_Asignacion_peticion/$', login_required(newAsignacionPeticion), name='nuevo_asignacion_peticion'),
    url(r'^mostrar_Asignacion_peticion/$', login_required(verAsignacionPeticion), name='mostrar_asignacion_peticion'),
    url(r'^editar_Asignacion_peticion/(?P<id>\d+)$', login_required(editarAsignacionPeticion), name='editar_asignacion_peticion'),
    url(r'^eliminar_Asignacion_peticion/(?P<id>\d+)$', login_required(eliminarAsignacionPeticion), name='eliminar_asignacion_peticion'),
    url(r'^nuevo_Acuerdo_SLA/$', login_required(newAcuerdoSLA), name='nuevo_acuerdo'),
    url(r'^mostrar_Acuerdo_SLA/$', login_required(verAcuerdoSLA), name='mostrar_acuerdo'),
    url(r'^editar_Acuedo_SLA/(?P<id>\d+)$', login_required(editarAcuerdoSLA), name='editar_acuerdo'),
    url(r'^eliminar_Acuerdo_SLA/(?P<id>\d+)$', login_required(eliminarAcuerdoSLA), name='eliminar_acuerdo'),
    url(r'^nuevo_Seguimiento_peticion/$', login_required(newSeguimientoPeticion), name='nuevo_seguimiento_peticion'),
    url(r'^mostrar_Seguimiento_peticion/$', login_required(verSeguimientoPeticion), name='mostrar_seguimiento_peticion'),
    url(r'^editar_Seguimiento_peticion/(?P<id>\d+)$', login_required(editarSeguimientoPeticion), name='editar_seguimiento_peticion'),
    url(r'^eliminar_Seguimiento_peticion/(?P<id>\d+)$', login_required(eliminarSeguimientoPeticion), name='eliminar_seguimiento_peticion'),
    url(r'^nuevo_Cierre_peticion/$', login_required(newCierrePeticion), name='nuevo_cierre_peticion'),
    url(r'^mostrar_Cierre_peticion/$', login_required(verCierrePeticion), name='mostrar_cierre_peticion'),
    url(r'^editar_Cierre_peticion/(?P<id>\d+)$', login_required(editarCierrePeticion), name='editar_cierre_peticion'),
    url(r'^eliminar_Cierre_peticion/(?P<id>\d+)$', login_required(eliminarCierrePeticion), name='eliminar_cierre_peticion'),
#Entrega
    url(r'^nueva_Entrega/$', login_required(newEntrega), name='nuevo_entrega'),
    url(r'^mostrar_Entrega/$', login_required(verEntrega), name='mostrar_entrega'),
    url(r'^editar_Entrega/(?P<id>\d+)$', login_required(editarEntrega), name='editar_entrega'),
    url(r'^eliminar_Entrega/(?P<id>\d+)$', login_required(eliminarEntrega), name='eliminar_entrega'),
#Problema
    url(r'^nuevo_Problema/$', login_required(newProblema), name='nuevo_problema'),
    url(r'^mostrar_Problema/$', login_required(verProblema), name='mostrar_problema'),
    url(r'^editar_Problema/(?P<id>\d+)$', login_required(editarProblema), name='editar_problema'),
    url(r'^eliminar_Problema/(?P<id>\d+)$', login_required(eliminarProblema), name='eliminar_problema'),
    url(r'^nueva_Asignacion_problema/$', login_required(newAsignacionProblema), name='nuevo_asignacion_problema'),
    url(r'^mostrar_Asignacion_problema/$', login_required(verAsignacionProblema), name='mostrar_asignacion_problema'),
    url(r'^editar_Asignacion_problema/(?P<id>\d+)$', login_required(editarAsignacionProblema), name='editar_asignacion_problema'),
    url(r'^eliminar_Asignacion_problema/(?P<id>\d+)$', login_required(eliminarAsignacionProblema), name='eliminar_asignacion_problema'),
    url(r'^nuevo_Seguimiento_problema/$', login_required(newSeguimientoProblema), name='nuevo_seguimiento_problema'),
    url(r'^mostrar_Seguimiento_problema/$', login_required(verSeguimientoProblema), name='mostrar_seguimiento_problema'),
    url(r'^editar_Seguimiento_problema/(?P<id>\d+)$', login_required(editarSeguimientoProblema), name='editar_seguimiento_problema'),
    url(r'^eliminar_Seguimiento_problema/(?P<id>\d+)$', login_required(eliminarSeguimientoProblema), name='eliminar_seguimiento_problema'),
    url(r'^nuevo_Cierre_problema/$', login_required(newCierreProblema), name='nuevo_cierre_problema'),
    url(r'^mostrar_Cierre_problema/$', login_required(verCierreProblema), name='mostrar_cierre_problema'),
    url(r'^editar_Cierre_problema/(?P<id>\d+)$', login_required(editarCierreProblema), name='editar_cierre_problema'),
    url(r'^eliminar_Cierre_problema/(?P<id>\d+)$', login_required(eliminarCierreProblema), name='eliminar_cierre_problema'),
#Proveedores
    url(r'^nuevo_Desempeno/$', login_required(newDesempeno), name='nuevo_desempeno'),
    url(r'^mostrar_Desempeno/$', login_required(verDesempeno), name='mostrar_desempeno'),
    url(r'^editar_Desempeno/(?P<id>\d+)$', login_required(editarDesempeno), name='editar_desempeno'),
    url(r'^eliminar_Desempeno/(?P<id>\d+)$', login_required(eliminarDesempeno), name='eliminar_desempeno'),
    url(r'^nueva_Ponderacion/$', login_required(newPonderacion), name='nuevo_ponderacion'),
    url(r'^mostrar_Ponderacion/$', login_required(verPonderacion), name='mostrar_ponderacion'),
    url(r'^editar_Ponderacion/(?P<id>\d+)$', login_required(editarPonderacion), name='editar_ponderacion'),
    url(r'^eliminar_Ponderacion/(?P<id>\d+)$', login_required(eliminarPonderacion), name='eliminar_ponderacion'),
    url(r'^nuevo_Inicio_evaluacion/$', login_required(newEvaluacion), name='nuevo_inicio_evaluacion'),
    url(r'^mostrar_Inicio_evaluacion/$', login_required(verEvaluacion), name='mostrar_inicio_evaluacion'),
    url(r'^editar_Inicio_evaluacion/(?P<id>\d+)$', login_required(editarEvaluacion), name='editar_inicio_evaluacion'),
    url(r'^eliminar_Inicio_evaluacion/(?P<id>\d+)$', login_required(eliminarEvaluacion), name='eliminar_inicio_evaluacion'),
    url(r'^nueva_Evaluacion_proveedor/$', login_required(newEvaluacionProveedor), name='nuevo_evaluacion_proveedor'),
    url(r'^mostrar_Evaluacion_proveedor/$', login_required(verEvaluacionProveedor), name='mostrar_evaluacion_proveedor'),
    url(r'^editar_Evaluacion_proveedor/(?P<id>\d+)$', login_required(editarEvaluacionProveedor), name='editar_evaluacion_proveedor'),
    url(r'^eliminar_Evaluacion_proveedor/(?P<id>\d+)$', login_required(eliminarEvaluacionProveedor), name='eliminar_evaluacion_proveedor'),
    url(r'^nueva_Reevaluacion_proveedor/$', login_required(newReevaluacionProveedor), name='nuevo_reevaluacion_proveedor'),
    url(r'^mostrar_Reevaluacion_proveedor/$', login_required(verReevaluacionProveedor), name='mostrar_reevaluacion_proveedor'),
    url(r'^editar_Reevaluacion_proveedor/(?P<id>\d+)$', login_required(editarReevaluacionProveedor), name='editar_reevaluacion_proveedor'),
    url(r'^eliminar_Reevaluacion_proveedor/(?P<id>\d+)$', login_required(eliminarReevaluacionProveedor), name='eliminar_reevaluacion_proveedor'),
#clientes
    url(r'^nueva_Pregunta/$', login_required(newPregunta), name='nuevo_pregunta'),
    url(r'^mostrar_Pregunta/$', login_required(verPregunta), name='mostrar_pregunta'),
    url(r'^editar_Pregunta/(?P<id>\d+)$', login_required(editarPregunta), name='editar_pregunta'),
    url(r'^eliminar_Pregunta/(?P<id>\d+)$', login_required(eliminarPregunta), name='eliminar_pregunta'),
    url(r'^nuevo_Cliente/$', login_required(newCliente), name='nuevo_cliente'),
    url(r'^mostrar_Cliente/$', login_required(verCliente), name='mostrar_cliente'),
    url(r'^editar_Cliente/(?P<id>\d+)$', login_required(editarCliente), name='editar_cliente'),
    url(r'^eliminar_Cliente/(?P<id>\d+)$', login_required(eliminarCliente), name='eliminar_cliente'),
    url(r'^nueva_Encuesta/$', login_required(newEncuesta), name='nuevo_encuesta'),
    url(r'^mostrar_Encuesta/$', login_required(verEncuesta), name='mostrar_encuesta'),
    url(r'^editar_Encuesta/(?P<id>\d+)$', login_required(editarEncuesta), name='editar_encuesta'),
    url(r'^eliminar_Encuesta/(?P<id>\d+)$', login_required(eliminarEncuesta), name='eliminar_encuesta'),
    url(r'^nueva_Reclamacion/$', login_required(newReclamacion), name='nuevo_reclamacion'),
    url(r'^mostrar_Reclamacion/$', login_required(verReclamacion), name='mostrar_reclamacion'),
    url(r'^editar_Reclamacion/(?P<id>\d+)$', login_required(editarReclamacion), name='editar_reclamacion'),
    url(r'^eliminar_Reclamacion/(?P<id>\d+)$', login_required(eliminarReclamacion), name='eliminar_reclamacion'),
    url(r'^nueva_Asignacion_reclamacion/$', login_required(newAsignacionReclamacion), name='nuevo_asignacion_reclamacion'),
    url(r'^mostrar_Asignacion_reclamacion/$', login_required(verAsignacionReclamacion), name='mostrar_asignacion_reclamacion'),
    url(r'^editar_Asignacion_reclamacion/(?P<id>\d+)$', login_required(editarAsignacionReclamacion), name='editar_asignacion_reclamacion'),
    url(r'^eliminar_Asignacion_reclamacion/(?P<id>\d+)$', login_required(eliminarAsignacionReclamacion), name='eliminar_asignacion_reclamacion'),
    url(r'^nueva_Asignacion_encuesta/$', login_required(newAsignacionEncuesta), name='nuevo_asignacion_encuesta'),
    url(r'^mostrar_Asignacion_encuesta/$', login_required(verAsignacionEncuesta), name='mostrar_asignacion_encuesta'),
    url(r'^editar_Asignacion_encuesta/(?P<id>\d+)$', login_required(editarAsignacionEncuesta), name='editar_asignacion_encuesta'),
    url(r'^eliminar_Asignacion_encuesta/(?P<id>\d+)$', login_required(eliminarAsignacionEncuesta), name='eliminar_asignacion_encuesta'),
#seguridad
    url(r'^nuevo_Activo/$', login_required(newActivo), name='nuevo_activo'),
    url(r'^mostrar_Activo/$', login_required(verActivo), name='mostrar_activo'),
    url(r'^editar_Activo/(?P<id>\d+)$', login_required(editarActivo), name='editar_activo'),
    url(r'^eliminar_Activo/(?P<id>\d+)$', login_required(eliminarActivo), name='eliminar_activo'),
    url(r'^nueva_Amenaza/$', login_required(newAmenaza), name='nuevo_amenaza'),
    url(r'^mostrar_Amenaza/$', login_required(verAmenaza), name='mostrar_amenaza'),
    url(r'^editar_Amenaza/(?P<id>\d+)$', login_required(editarAmenaza), name='editar_amenaza'),
    url(r'^eliminar_Amenaza/(?P<id>\d+)$', login_required(eliminarAmenaza), name='eliminar_amenaza'),
    url(r'^nuevo_Riesgo/$', login_required(newRiesgo), name='nuevo_riesgo'),
    url(r'^mostrar_Riesgo/$', login_required(verRiesgo), name='mostrar_riesgo'),
    url(r'^editar_Riesgo/(?P<id>\d+)$', login_required(editarRiesgo),name='editar_riesgo'),
    url(r'^eliminar_Riesgo/(?P<id>\d+)$', login_required(eliminarRiesgo), name='eliminar_riesgo'),
    url(r'^nuevo_Analisis_riesgo/$', login_required(newAnalisisRiesgo), name='nuevo_analisis_riesgo'),
    url(r'^mostrar_Analisis_riesgo/$', login_required(verAnalisisRiesgo), name='mostrar_analisis_riesgo'),
    url(r'^editar_Analisis_riesgo/(?P<id>\d+)$', login_required(editarAnalisisRiesgo), name='editar_analisis_riesgo'),
    url(r'^eliminar_Analisis_riesgo/(?P<id>\d+)$', login_required(eliminarAnalisisRiesgo), name='eliminar_analisis_riesgo'),
    url(r'^nueva_Prioridad_riesgo/$', login_required(newPrioridadRiesgo), name='nuevo_prioridad_riesgo'),
    url(r'^mostrar_Prioridad_riesgo/$', login_required(verPrioridadRiesgo), name='mostrar_prioridad_riesgo'),
    url(r'^editar_Prioridad_riesgo/(?P<id>\d+)$', login_required(editarPrioridadRiesgo), name='editar_prioridad_riesgo'),
    url(r'^eliminar_Prioridad_riesgo/(?P<id>\d+)$', login_required(eliminarPrioridadRiesgo), name='eliminar_prioridad_riesgo'),
    url(r'^nueva_Calificacion_conocimientos/$', login_required(newCalificacion), name='nuevo_calificacion'),
    url(r'^mostrar_Calificacion_conocimientos/$', login_required(verCalificacion), name='mostrar_calificacion'),
    url(r'^editar_Calificacion_conocimientos/(?P<id>\d+)$', login_required(editarCalificacion), name='editar_calificacion'),
    url(r'^eliminar_Calificacion_conocimientos/(?P<id>\d+)$', login_required(eliminarCalificacion), name='eliminar_calificacion'),
    url(r'^nuevo_Cuestionario/$', login_required(newCuestionario), name='nuevo_cuestionario'),
    url(r'^mostrar_Cuestionario/$', login_required(verCuestionario), name='mostrar_cuestionario'),
    url(r'^editar_Cuestionario/(?P<id>\d+)$', login_required(editarCuestionario), name='editar_cuestionario'),
    url(r'^eliminar_Cuestionario/(?P<id>\d+)$', login_required(eliminarCuestionario), name='eliminar_cuestionario'),
    url(r'^nuevo_Resultado_cuestionario/$', login_required(newResultadoCuestionario), name='nuevo_resultado_cuestionario'),
    url(r'^mostrar_Resultado_cuestionario/$', login_required(verResultadoCuestionario), name='mostrar_resultado_cuestionario'),
    url(r'^editar_Resultado_cuestionario/(?P<id>\d+)$', login_required(editarResultadoCuestionario), name='editar_resultado_cuestionario'),
    url(r'^eliminar_Resultado_cuestionario/(?P<id>\d+)$', login_required(eliminarResultadoCuestionario), name='eliminar_resultado_cuestionario'),
    url(r'^nueva_Auditoria_seguridad/$', login_required(newAuditoriaSeguridad), name='nuevo_auditoria_seguridad'),
    url(r'^mostrar_Auditoria_seguridad/$', login_required(verAuditoriaSeguridad), name='mostrar_auditoria_seguridad'),
    url(r'^editar_Auditoria_seguridad/(?P<id>\d+)$', login_required(editarAuditoriaSeguridad), name='editar_auditoria_seguridad'),
    url(r'^eliminar_Auditoria_seguridad/(?P<id>\d+)$', login_required(eliminarAuditoriaSeguridad), name='eliminar_auditoria_seguridad'),
    url(r'^nuevo_Checklist_seguridad/$', login_required(newChecklistSeguridad), name='nuevo_checklist_seguridad'),
    url(r'^mostrar_Checklist_seguridad/$',verChecklistSeguridad,name='mostrar_checklist_seguridad'),
    url(r'^editar_Checklist_seguridad/(?P<id>\d+)$', login_required(editarChecklistSeguridad), name='editar_checklist_seguridad'),
    url(r'^eliminar_Checklist_seguridad/(?P<id>\d+)$', login_required(eliminarChecklistSeguridad), name='eliminar_checklist_seguridad'),
    url(r'^nuevo_Resultado_checklist/$', login_required(newResultadoSeguridad), name='nuevo_resultado_seguridad'),
    url(r'^mostrar_Resultado_checklist/$', login_required(verResultadoSeguridad), name='mostrar_resultado_seguridad'),
    url(r'^editar_Resultado_checklist/(?P<id>\d+)$', login_required(editarResultadoSeguridad), name='editar_resultado_seguridad'),
    url(r'^eliminar_Resultado_checklist/(?P<id>\d+)$', login_required(eliminarResultadoSeguridad), name='eliminar_resultado_seguridad'),
#Resumenes
    url(r'^mostrar_Resumen_configuracion/$', login_required(verResumenConfiguracion), name='mostrar_resumen_configuracion'),
    url(r'^mostrar_Resumen_cambios/$', login_required(verResumenCambios), name='mostrar_resumen_cambios'),
    url(r'^mostrar_Resumen_problemas/$', login_required(verResumenProblemas), name='mostrar_resumen_problemas'),
    url(r'^mostrar_Resumen_peticiones/$', login_required(verResumenPeticiones), name='mostrar_resumen_peticiones'),
    
    url(r'^mostrar_Resumen_proveedores/$', login_required(verResumenProveedores), name='mostrar_resumen_proveedores'),
    url(r'^mostrar_Resumen_clientes/$', login_required(verResumenClientes), name='mostrar_resumen_clientes'),
    url(r'^mostrar_Resumen_seguridad/$', login_required(verResumenSeguridad), name='mostrar_resumen_seguridad'),
#popups
    url(r'^agregar_marca/$', login_required(CreateMarca.as_view()), name='add_marca'),
    url(r'^agregar_modelo/$', login_required(CreateModelo.as_view()), name='add_modelo'),
    url(r'^agregar_organizacion/$', login_required(CreateOrganizacion.as_view()), name='add_organizacion'),
    url(r'^agregar_contacto/$', login_required(CreateContacto.as_view()), name='add_contacto'),
    url(r'^agregar_producto/$', login_required(CreateProducto.as_view()), name='add_producto'),
    url(r'^agregar_peticion/$', login_required(CreatePeticion.as_view()), name='add_peticion'),
    url(r'^agregar_evaluacion/$', login_required(CreateEvaluacion.as_view()), name='add_evaluacion'),
    url(r'^agregar_evaluacion_proveedores/$', login_required(CreateEvaluacionProveedores.as_view()), name='add_evaluacion_proveedor'),
#modal
    url(r'^create_peticion/$', login_required(create_peticion)),
    url(r'^create_contacto/$', login_required(create_contacto)),
#inlines
    url(r'^crear_Peticion/$', login_required(PeticionCreateView.as_view())),
    url(r'^peticion/(?P<id>\d+)/$', login_required(PeticionUpdateView.as_view())),
    url(r'^crear_Problema/$', login_required(ProblemaCreateView.as_view())),
    url(r'^problema/(?P<id>\d+)/$', login_required(ProblemaUpdateView.as_view())),
    url(r'^crear_Cambio/$', login_required(CambioCreateView.as_view())),
    url(r'^cambio/(?P<id>\d+)/$', login_required(CambioUpdateView.as_view())),
    url(r'^mostrar_Elementos_configuracion/$', login_required(allEC), name='all_EC'),
    url(r'^crear_Impresora/$', login_required(ImpresoraCreateView.as_view())),
    url(r'^impresora/(?P<id>\d+)/$', login_required(ImpresoraUpdateView.as_view())),
    url(r'^crear_Granja/$', login_required(GranjaCreateView.as_view())),
    url(r'^granja/(?P<id>\d+)/$', login_required(GranjaUpdateView.as_view())),
    url(r'^crear_Maquina_virtual/$', login_required(MaquinaCreateView.as_view())),
    url(r'^maquina_virtual/(?P<id>\d+)/$', login_required(MaquinaUpdateView.as_view())),
    url(r'^crear_Licencia/$', login_required(LicenciaCreateView.as_view())),
    url(r'^licencia/(?P<id>\d+)/$', login_required(LicenciaUpdateView.as_view())),
    url(r'^crear_Vlan/$', login_required(VlanCreateView.as_view())),
    url(r'^vlan/(?P<id>\d+)/$', login_required(VlanUpdateView.as_view())),
    url(r'^crear_Contacto/$', login_required(ContactoCreateView.as_view())),
    url(r'^contacto/(?P<id>\d+)/$', login_required(ContactoUpdateView.as_view())),
    url(r'^crear_PC_Laptop/$', login_required(PCCreateView.as_view())),
    url(r'^pc_laptop/(?P<id>\d+)/$', login_required(PCUpdateView.as_view())),
    url(r'^crear_Instalacion_software/$', login_required(InstalacionCreateView.as_view())),
    url(r'^instalacion_software/(?P<id>\d+)/$', login_required(InstalacionUpdateView.as_view())),
    url(r'^crear_Rack/$', login_required(RackCreateView.as_view())),
    url(r'^rack/(?P<id>\d+)/$', login_required(RackUpdateView.as_view())),
    url(r'^crear_Servidor/$', login_required(ServidorCreateView.as_view())),
    url(r'^servidor/(?P<id>\d+)/$', login_required(ServidorUpdateView.as_view())),
    url(r'^crear_Hypervisor/$', login_required(HypervisorCreateView.as_view())),
    url(r'^hypervisor/(?P<id>\d+)/$', login_required(HypervisorUpdateView.as_view())),
    url(r'^crear_Telefono_Celular/$', login_required(TelefonoCreateView.as_view())),
    url(r'^telefono_celular/(?P<id>\d+)/$', login_required(TelefonoUpdateView.as_view())),
    url(r'^crear_Dispositivo_red/$', login_required(DispositivoCreateView.as_view())),
    url(r'^dispositivo_red/(?P<id>\d+)/$', login_required(DispositivoUpdateView.as_view())),
    url(r'^crear_Interfaz_red/$', login_required(InterfazCreateView.as_view())),
    url(r'^interfaz_red/(?P<id>\d+)/$', login_required(InterfazUpdateView.as_view())),
    url(r'^crear_Reclamacion/$', login_required(ReclamacionCreateView.as_view())),
    url(r'^reclamacion/(?P<id>\d+)/$', login_required(ReclamacionUpdateView.as_view())),

#crear encuesta "cliente"
    #url(r'^crear_Encuesta/$',crearEncuesta,name='crear_encuesta'),
    url(r'^encuesta/(?P<id>\d+)/$', login_required(answer_form)),

    #url(r'^crear_Evaluacion/$',crearEvaluacion,name='crear_evaluacion'),
    url(r'^evaluacion/(?P<id>\d+)/$', login_required(answer_form2)),

]
