# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=200, unique=True)),
                ('clase', models.CharField(max_length=200, unique=True)),
                ('confidencialidad', models.PositiveIntegerField(blank=True, null=True)),
                ('integridad', models.PositiveIntegerField(blank=True, null=True)),
                ('disponibilidad', models.PositiveIntegerField(blank=True, null=True)),
                ('valor', models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Acuerdo_SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solucion', models.DateField()),
                ('costo', models.PositiveIntegerField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[(b'Pesos', b'Pesos'), (b'Dolares', b'Dolares')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alcance', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amenazas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenaza', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('vulnerabilidad', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analisis_Riesgos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(blank=True, null=True)),
                ('costo', models.CharField(choices=[(b'Bajo', b'Bajo'), (b'Medio', b'Medio'), (b'Alto', b'Alto')], max_length=200)),
                ('recursos', models.CharField(choices=[(b'Bajo', b'Bajo'), (b'Medio', b'Medio'), (b'Alto', b'Alto')], max_length=200)),
                ('estado_accion', models.CharField(choices=[(b'Abierto', b'Abierto'), (b'En proceso', b'En proceso'), (b'Implementado', b'Implementado')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_Peticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_resolucion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_Reclamacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria_EC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateField()),
                ('total_elementos', models.PositiveIntegerField(blank=True, null=True)),
                ('total_productivo', models.PositiveIntegerField(blank=True, null=True)),
                ('total_alta', models.PositiveIntegerField(blank=True, null=True)),
                ('total_media', models.PositiveIntegerField(blank=True, null=True)),
                ('total_baja', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria_Seguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_proxima', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[(b'Muy bien', b'Muy bien'), (b'Bien', b'Bien'), (b'Suficiente', b'Suficiente'), (b'Bajo', b'Bajo')], max_length=200, unique=True)),
                ('puntos_respuesta', models.PositiveIntegerField()),
                ('puntos_cuestionario', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion_Seguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[(b'Parcial', b'Parcial'), (b'No implementado', b'No implementado'), (b'Implementado', b'Implementado')], max_length=200)),
                ('puntos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Checklist_Auditoria_Seguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=200, null=True)),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('puntos', models.PositiveIntegerField(editable=False)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Auditoria_Seguridad')),
            ],
        ),
        migrations.CreateModel(
            name='Cierre_Peticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.TextField(blank=True, max_length=200, null=True)),
                ('fecha_cierre', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cierre_Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion_EC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clasificacion', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('apellido_contacto', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=False)),
                ('funcion', models.CharField(blank=True, max_length=200, null=True)),
                ('jefe', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.EmailField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.SmallIntegerField(blank=True, choices=[(0, 'Muy poco'), (1, 'Poco'), (2, 'Medio'), (3, 'Mucho'), (4, 'Totalmente')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionario_Seguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_respuesta', models.TextField(blank=True, null=True)),
                ('puntos', models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Desempeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, unique=True)),
                ('porcentaje', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo_Red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dispositivo', models.CharField(max_length=200, unique=True)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('ram', models.CharField(blank=True, max_length=200, null=True)),
                ('unidades_rack', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ec', models.CharField(max_length=200, unique=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Clasificacion_EC')),
            ],
        ),
        migrations.CreateModel(
            name='Encargados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'grupo', chained_model_field=b'grupo', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Encuestado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_encuesta', models.DateField()),
                ('calificacion', models.PositiveIntegerField(blank=True, default=0)),
                ('estado', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field=b'organizacion', chained_model_field=b'organizacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega_Peticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_factura', models.DateField()),
                ('chofer', models.CharField(blank=True, max_length=200, null=True)),
                ('firma', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_entrega', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma', models.CharField(blank=True, max_length=200, null=True)),
                ('que_sucedio', models.CharField(blank=True, max_length=200, null=True)),
                ('por_que_sucedio', models.CharField(blank=True, max_length=200, null=True)),
                ('que_puede_hacerse', models.CharField(blank=True, max_length=200, null=True)),
                ('solucion_temporal', models.CharField(blank=True, max_length=200, null=True)),
                ('solucion_final', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_proxima_evaluacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('total_incidentes', models.PositiveIntegerField(editable=False)),
                ('calificacion', models.PositiveIntegerField(blank=True, default=0)),
                ('estado2', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exclusivo_Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[(b'Actualizacion de Infraestructura', b'Actualizacion de Infraestructura'), (b'Infraestructura', b'Infraestructura'), (b'Proposito de Mejora', b'Proposito de Mejora'), (b'Nuevo Servicio', b'Nuevo Servicio'), (b'Modificacion de Servicio', b'Modificacion de Servicio'), (b'Gestion de Problema', b'Gestion de Problema')], max_length=200)),
                ('estado', models.CharField(choices=[(b'Aprobada', b'Aprobada'), (b'En Espera', b'En Espera'), (b'Rechazado', b'Rechazado')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='General_Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('criticidad', models.CharField(choices=[(b'Alto', b'Alto'), (b'Medio', b'Medio'), (b'Bajo', b'Bajo')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_granja', models.CharField(max_length=200, unique=True)),
                ('fecha_produccion', models.DateField()),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_EC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=200, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hypervisor', models.CharField(max_length=200, unique=True)),
                ('fecha_produccion', models.DateField()),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
                ('granja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Granja')),
            ],
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_impresora', models.CharField(max_length=200, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_compra', models.DateField()),
                ('fecha_produccion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion_Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_instalacion', models.DateField()),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
            ],
        ),
        migrations.CreateModel(
            name='Interfaz_Red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interfaz', models.CharField(max_length=200, unique=True)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('mac', models.CharField(blank=True, max_length=200, null=True)),
                ('gateway', models.CharField(blank=True, max_length=200, null=True)),
                ('mascara', models.CharField(blank=True, max_length=200, null=True)),
                ('velocidad', models.CharField(blank=True, max_length=200, null=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Dispositivo_Red')),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_licencia', models.CharField(max_length=200, unique=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('llave', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_localidad', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200, unique=True)),
                ('cp', models.PositiveIntegerField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('pais', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina_Virtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maquina', models.CharField(max_length=200, unique=True)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu', models.CharField(blank=True, max_length=200, null=True)),
                ('ram', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_produccion', models.DateField()),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
                ('granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Granja')),
                ('licencia', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'version', chained_model_field=b'version', on_delete=django.db.models.deletion.CASCADE, to='home.Licencia')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marcha_Atras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recursos', models.CharField(blank=True, max_length=200, null=True)),
                ('tiempo', models.CharField(blank=True, max_length=200, null=True)),
                ('procedimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_plan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=200, unique=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=200, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_origen', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PC_Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=200)),
                ('laptop', models.BooleanField(default=False)),
                ('cpu', models.CharField(blank=True, max_length=200, null=True)),
                ('ram', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_compra', models.DateField()),
                ('fecha_produccion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('contacto', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'organizacion', chained_model_field=b'organizacion', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado')),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Marca')),
                ('modelo', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'marca', chained_model_field=b'marca', on_delete=django.db.models.deletion.CASCADE, to='home.Modelo')),
                ('organizacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[(b'Correo', b'Correo'), (b'Monitoreo', b'Monitoreo'), (b'Telefono', b'Telefono'), (b'Portal', b'Portal')], max_length=200)),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('impacto', models.CharField(choices=[(b'Departamento', b'Departamento'), (b'Servicio', b'Servicio'), (b'Persona', b'Persona')], max_length=200)),
                ('urgencia', models.CharField(choices=[(b'Baja', b'Baja'), (b'Media', b'Media'), (b'Alta', b'Alta'), (b'Critica', b'Critica')], max_length=200)),
                ('contacto', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'organizacion', chained_model_field=b'organizacion', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado')),
                ('organizacion', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo_contacto', chained_model_field=b'contacto', on_delete=django.db.models.deletion.CASCADE, to='home.Organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion_Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_impacto', models.CharField(blank=True, max_length=200, null=True)),
                ('duracion_impacto', models.CharField(blank=True, max_length=200, null=True)),
                ('costo_impacto', models.CharField(blank=True, max_length=200, null=True)),
                ('prioridad', models.CharField(choices=[(b'Baja', b'Baja'), (b'Normal', b'Normal'), (b'Alta', b'Alta'), (b'Urgente', b'Urgente')], max_length=200)),
                ('categoria', models.CharField(choices=[(b'Rutina', b'Rutina'), (b'Normal', b'Normal'), (b'Urgente', b'Urgente')], max_length=200)),
                ('descripcion_aprobado', models.TextField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('area_implicada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_minimo_incidentes', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[(b'Insuficiente', b'Insuficiente'), (b'Suficiente', b'Suficiente'), (b'Bueno', b'Bueno'), (b'Muy bueno', b'Muy bueno')], max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad_Riesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_maximo_riesgo', models.PositiveIntegerField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[(b'Baja', b'Baja'), (b'Media', b'Media'), (b'Mayor', b'Mayor')], max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto_problema', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_problema', models.TextField(blank=True, null=True)),
                ('impacto', models.CharField(choices=[(b'Departamento', b'Departamento'), (b'Servicio', b'Servicio'), (b'Persona', b'Persona')], max_length=200)),
                ('urgencia', models.CharField(choices=[(b'Baja', b'Baja'), (b'Media', b'Media'), (b'Alta', b'Alta'), (b'Critica', b'Critica')], max_length=200)),
                ('peticion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Peticion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_producto', models.CharField(blank=True, max_length=200, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Marca')),
                ('modelo', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'marca', chained_model_field=b'marca', on_delete=django.db.models.deletion.CASCADE, to='home.Modelo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Peticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('peticion', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo', chained_model_field=b'peticion', on_delete=django.db.models.deletion.CASCADE, to='home.Peticion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.SmallIntegerField(blank=True, choices=[(0, 'Nunca'), (1, 'Pocas veces'), (2, 'Frecuentemente'), (3, 'Siempre')], null=True)),
                ('evaluacion_proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Evaluacion_Proveedores')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[(b'Nunca', b'Nunca'), (b'Pocas veces', b'Pocas veces'), (b'Frecuentemente', b'Frecuentemente'), (b'Siempre', b'Siempre')], max_length=200, unique=True)),
                ('puntos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rack', models.CharField(max_length=200, unique=True)),
                ('unidades_rack', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_compra', models.DateField()),
                ('fecha_produccion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Marca')),
                ('modelo', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'marca', chained_model_field=b'marca', on_delete=django.db.models.deletion.CASCADE, to='home.Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('motivo_reclamacion', models.CharField(max_length=200)),
                ('valor_importancia', models.CharField(choices=[(b'Baja', b'Baja'), (b'Media', b'Media'), (b'Alta', b'Alta'), (b'Critica', b'Critica')], max_length=200)),
                ('contacto', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'organizacion', chained_model_field=b'organizacion', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado')),
                ('organizacion', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo_contacto', chained_model_field=b'contacto', on_delete=django.db.models.deletion.CASCADE, to='home.Organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_red', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reevaluacion_Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Desempeno')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Evaluacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Lista_Proveedores')),
                ('puntaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Puntaje')),
            ],
        ),
        migrations.CreateModel(
            name='Responsables_Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acciones', models.TextField(blank=True, null=True)),
                ('fecha_revision_accion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[(b'Muy poco', b'Muy poco'), (b'Poco', b'Poco'), (b'Medio', b'Medio'), (b'Mucho', b'Mucho'), (b'Totalmente', b'Totalmente')], max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(editable=False)),
                ('estado', models.CharField(editable=False, max_length=200)),
                ('encuestado', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'proceso', chained_model_field=b'proceso', on_delete=django.db.models.deletion.CASCADE, to='home.Encuestado', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados_Auditoria_Seguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(editable=False)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Auditoria_Seguridad', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reunion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Riesgos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.PositiveIntegerField(blank=True, null=True)),
                ('impacto', models.PositiveIntegerField(blank=True, null=True)),
                ('valor', models.PositiveIntegerField(editable=False)),
                ('calculo_riesgo', models.PositiveIntegerField(editable=False)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Activos')),
                ('amenaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Amenazas')),
                ('prioridad', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.Prioridad_Riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento_Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField()),
                ('descripcion_seguimiento', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento_Peticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True, max_length=200, null=True)),
                ('peticion', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo', chained_model_field=b'peticion', on_delete=django.db.models.deletion.CASCADE, to='home.Peticion')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento_Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Problema')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('alcance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Alcance')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servidor', models.CharField(max_length=200, unique=True)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu', models.CharField(blank=True, max_length=200, null=True)),
                ('ram', models.CharField(blank=True, max_length=200, null=True)),
                ('unidades_rack', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_compra', models.DateField()),
                ('fecha_produccion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Licencia')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Marca')),
                ('modelo', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'marca', chained_model_field=b'marca', on_delete=django.db.models.deletion.CASCADE, to='home.Modelo')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Rack')),
            ],
        ),
        migrations.CreateModel(
            name='SO_Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_software', models.CharField(max_length=200, unique=True)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('sistema_operativo', models.BooleanField(default=False)),
                ('nombre_ec', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='home.EC')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estimacion_recursos', models.CharField(choices=[(b'Alto', b'Alto'), (b'Medio', b'Medio'), (b'Bajo', b'Bajo')], max_length=200)),
                ('tiempo_cambio', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'grupo', chained_model_field=b'grupo', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subcategoria', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_Celular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.BooleanField(default=False)),
                ('numero_telefono', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_produccion', models.DateField()),
                ('contacto', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'organizacion', chained_model_field=b'organizacion', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado')),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Marca')),
                ('modelo', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'marca', chained_model_field=b'marca', on_delete=django.db.models.deletion.CASCADE, to='home.Modelo')),
                ('organizacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(choices=[(b'Cliente', b'Cliente'), (b'Prestador de Servicios', b'Prestador de Servicios')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Peticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_peticion', models.CharField(blank=True, choices=[(b'Requerimiento', b'Requerimiento'), (b'Incidente', b'Incidente')], max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proceso', models.CharField(choices=[(b'Recurso', b'Recurso'), (b'Cliente', b'Cliente'), (b'Seguridad', b'Seguridad'), (b'Auditoria de Seguridad', b'Auditoria de Seguridad'), (b'Proveedor', b'Proveedor')], max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitud', models.CharField(choices=[(b'Cambio', b'Cambio'), (b'Mejora', b'Mejora')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Verificacion_Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_verificacion', models.DateField()),
                ('eficacia', models.CharField(choices=[(b'Alta', b'Alta'), (b'Media', b'Media'), (b'Baja', b'Baja')], max_length=200)),
                ('descripcion_eficacia', models.TextField(blank=True, max_length=200, null=True)),
                ('folio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Solicitud_Cambio')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_version', models.CharField(max_length=200)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SO_Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vlan', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion')),
            ],
        ),
        migrations.AddField(
            model_name='servidor',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.SO_Programa'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='version',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field=b'software', chained_model_field=b'software', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Version'),
        ),
        migrations.AddField(
            model_name='seguimiento_cambio',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Solicitud_Cambio'),
        ),
        migrations.AddField(
            model_name='seguimiento_cambio',
            name='responsabilidad_encargado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'folio', chained_model_field=b'folio', on_delete=django.db.models.deletion.CASCADE, to='home.Responsables_Cambio'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Solicitud'),
        ),
        migrations.AddField(
            model_name='resultado_cuestionario',
            name='proceso',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='tipo_respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='responsables_cambio',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Solicitud_Cambio'),
        ),
        migrations.AddField(
            model_name='responsables_cambio',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC'),
        ),
        migrations.AddField(
            model_name='responsables_cambio',
            name='responsable',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'grupo', chained_model_field=b'grupo', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado'),
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Servicio'),
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='subcategoria',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'servicio', chained_model_field=b'servicio', on_delete=django.db.models.deletion.CASCADE, to='home.Subcategoria'),
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='tipo_contacto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Contacto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Servicio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'servicio', chained_model_field=b'servicio', on_delete=django.db.models.deletion.CASCADE, to='home.Subcategoria'),
        ),
        migrations.AddField(
            model_name='problema',
            name='producto',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'peticion', chained_model_field=b'peticion', on_delete=django.db.models.deletion.CASCADE, to='home.Productos_Peticion', unique=True),
        ),
        migrations.AddField(
            model_name='problema',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Lista_Proveedores'),
        ),
        migrations.AddField(
            model_name='problema',
            name='solicitud_cambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Solicitud_Cambio'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='tipo_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='planificacion_cambio',
            name='folio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Solicitud_Cambio'),
        ),
        migrations.AddField(
            model_name='planificacion_cambio',
            name='plan_marcha_atras',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Marcha_Atras'),
        ),
        migrations.AddField(
            model_name='planificacion_cambio',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Reunion'),
        ),
        migrations.AddField(
            model_name='peticion',
            name='peticion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Peticion'),
        ),
        migrations.AddField(
            model_name='peticion',
            name='tipo_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Contacto'),
        ),
        migrations.AddField(
            model_name='origen',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Solicitud'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Contacto'),
        ),
        migrations.AddField(
            model_name='maquina_virtual',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SO_Programa'),
        ),
        migrations.AddField(
            model_name='maquina_virtual',
            name='version',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'software', chained_model_field=b'software', on_delete=django.db.models.deletion.CASCADE, to='home.Version'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Organizacion'),
        ),
        migrations.AddField(
            model_name='lista_proveedores',
            name='localidad',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'organizacion', chained_model_field=b'organizacion', on_delete=django.db.models.deletion.CASCADE, to='home.Localidad'),
        ),
        migrations.AddField(
            model_name='lista_proveedores',
            name='organizacion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo_contacto', chained_model_field=b'contacto', on_delete=django.db.models.deletion.CASCADE, to='home.Organizacion'),
        ),
        migrations.AddField(
            model_name='lista_proveedores',
            name='tipo_contacto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Contacto'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.SO_Programa'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.EC'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='version',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'software', chained_model_field=b'software', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Version'),
        ),
        migrations.AddField(
            model_name='instalacion_software',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Licencia'),
        ),
        migrations.AddField(
            model_name='instalacion_software',
            name='pc_laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PC_Laptop'),
        ),
        migrations.AddField(
            model_name='instalacion_software',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SO_Programa'),
        ),
        migrations.AddField(
            model_name='instalacion_software',
            name='version',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'software', chained_model_field=b'software', on_delete=django.db.models.deletion.CASCADE, to='home.Version'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Marca'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='modelo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'marca', chained_model_field=b'marca', on_delete=django.db.models.deletion.CASCADE, to='home.Modelo'),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Servidor'),
        ),
        migrations.AddField(
            model_name='general_configuracion',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Localidad'),
        ),
        migrations.AddField(
            model_name='general_configuracion',
            name='nombre_ec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.EC'),
        ),
        migrations.AddField(
            model_name='general_configuracion',
            name='nombre_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC'),
        ),
        migrations.AddField(
            model_name='exclusivo_cambio',
            name='folio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Solicitud_Cambio'),
        ),
        migrations.AddField(
            model_name='evaluacion_proveedores',
            name='estado',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.Ponderacion'),
        ),
        migrations.AddField(
            model_name='evaluacion_proveedores',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='evaluacion_proveedores',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Lista_Proveedores'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Lista_Proveedores'),
        ),
        migrations.AddField(
            model_name='entrega_peticion',
            name='peticion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Peticion'),
        ),
        migrations.AddField(
            model_name='entrega_peticion',
            name='producto',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'peticion', chained_model_field=b'peticion', on_delete=django.db.models.deletion.CASCADE, to='home.Productos_Peticion', unique=True),
        ),
        migrations.AddField(
            model_name='encuestado',
            name='organizacion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo_contacto', chained_model_field=b'contacto', on_delete=django.db.models.deletion.CASCADE, to='home.Organizacion'),
        ),
        migrations.AddField(
            model_name='encuestado',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='encuestado',
            name='tipo_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Contacto'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='encuestado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo_proceso', chained_model_field=b'proceso', on_delete=django.db.models.deletion.CASCADE, to='home.Encuestado'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo_proceso', chained_model_field=b'tipo_pregunta', on_delete=django.db.models.deletion.CASCADE, to='home.Preguntas'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='respuesta',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo_proceso', chained_model_field=b'tipo_respuesta', on_delete=django.db.models.deletion.CASCADE, to='home.Respuestas'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tipo_proceso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='encargados',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC'),
        ),
        migrations.AddField(
            model_name='dispositivo_red',
            name='general',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion'),
        ),
        migrations.AddField(
            model_name='dispositivo_red',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Marca'),
        ),
        migrations.AddField(
            model_name='dispositivo_red',
            name='modelo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'marca', chained_model_field=b'marca', on_delete=django.db.models.deletion.CASCADE, to='home.Modelo'),
        ),
        migrations.AddField(
            model_name='dispositivo_red',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Rack'),
        ),
        migrations.AddField(
            model_name='dispositivo_red',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.SO_Programa'),
        ),
        migrations.AddField(
            model_name='dispositivo_red',
            name='tipo_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Red'),
        ),
        migrations.AddField(
            model_name='dispositivo_red',
            name='version',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field=b'software', chained_model_field=b'software', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Version'),
        ),
        migrations.AddField(
            model_name='cuestionario_seguridad',
            name='encuestado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'proceso', chained_model_field=b'proceso', on_delete=django.db.models.deletion.CASCADE, to='home.Encuestado'),
        ),
        migrations.AddField(
            model_name='cuestionario_seguridad',
            name='pregunta',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'proceso', chained_model_field=b'tipo_pregunta', on_delete=django.db.models.deletion.CASCADE, to='home.Preguntas'),
        ),
        migrations.AddField(
            model_name='cuestionario_seguridad',
            name='proceso',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='cuestionario_seguridad',
            name='puntaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Calificacion'),
        ),
        migrations.AddField(
            model_name='clientequestion',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='clienteanswer',
            name='encuestado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Encuestado'),
        ),
        migrations.AddField(
            model_name='clienteanswer',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Preguntas'),
        ),
        migrations.AddField(
            model_name='cliente_empleado',
            name='general',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.General_Configuracion'),
        ),
        migrations.AddField(
            model_name='cliente_empleado',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC'),
        ),
        migrations.AddField(
            model_name='cliente_empleado',
            name='organizacion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo_contacto', chained_model_field=b'contacto', on_delete=django.db.models.deletion.CASCADE, to='home.Organizacion'),
        ),
        migrations.AddField(
            model_name='cliente_empleado',
            name='tipo_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Contacto'),
        ),
        migrations.AddField(
            model_name='cierre_problema',
            name='error_conocido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Errores'),
        ),
        migrations.AddField(
            model_name='cierre_problema',
            name='problema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Problema'),
        ),
        migrations.AddField(
            model_name='cierre_peticion',
            name='peticion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Peticion'),
        ),
        migrations.AddField(
            model_name='checklist_auditoria_seguridad',
            name='encuestado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'proceso', chained_model_field=b'proceso', on_delete=django.db.models.deletion.CASCADE, to='home.Encuestado'),
        ),
        migrations.AddField(
            model_name='checklist_auditoria_seguridad',
            name='pregunta',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'proceso', chained_model_field=b'tipo_pregunta', on_delete=django.db.models.deletion.CASCADE, to='home.Preguntas'),
        ),
        migrations.AddField(
            model_name='checklist_auditoria_seguridad',
            name='proceso',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='checklist_auditoria_seguridad',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Calificacion_Seguridad'),
        ),
        migrations.AddField(
            model_name='auditoria_ec',
            name='nombre_ec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.EC'),
        ),
        migrations.AddField(
            model_name='asistencia_reunion',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Encargados'),
        ),
        migrations.AddField(
            model_name='asistencia_reunion',
            name='reunion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'solicitud', chained_model_field=b'solicitud', on_delete=django.db.models.deletion.CASCADE, to='home.Reunion'),
        ),
        migrations.AddField(
            model_name='asistencia_reunion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Solicitud'),
        ),
        migrations.AddField(
            model_name='asignacion_reclamacion',
            name='contacto',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'grupo', chained_model_field=b'grupo', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado'),
        ),
        migrations.AddField(
            model_name='asignacion_reclamacion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC'),
        ),
        migrations.AddField(
            model_name='asignacion_reclamacion',
            name='reclamacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Reclamacion'),
        ),
        migrations.AddField(
            model_name='asignacion_problema',
            name='contacto',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'grupo', chained_model_field=b'grupo', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado'),
        ),
        migrations.AddField(
            model_name='asignacion_problema',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC'),
        ),
        migrations.AddField(
            model_name='asignacion_problema',
            name='problema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Problema'),
        ),
        migrations.AddField(
            model_name='asignacion_peticion',
            name='contacto',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'grupo', chained_model_field=b'grupo', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado'),
        ),
        migrations.AddField(
            model_name='asignacion_peticion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC'),
        ),
        migrations.AddField(
            model_name='asignacion_peticion',
            name='peticion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo', chained_model_field=b'peticion', on_delete=django.db.models.deletion.CASCADE, to='home.Peticion', unique=True),
        ),
        migrations.AddField(
            model_name='asignacion_encuesta',
            name='contacto',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'grupo', chained_model_field=b'grupo', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado'),
        ),
        migrations.AddField(
            model_name='asignacion_encuesta',
            name='encuesta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Encuestado'),
        ),
        migrations.AddField(
            model_name='asignacion_encuesta',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC'),
        ),
        migrations.AddField(
            model_name='analisis_riesgos',
            name='contacto',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'grupo', chained_model_field=b'grupo', on_delete=django.db.models.deletion.CASCADE, to='home.Cliente_Empleado'),
        ),
        migrations.AddField(
            model_name='analisis_riesgos',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grupo_EC'),
        ),
        migrations.AddField(
            model_name='analisis_riesgos',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Proceso'),
        ),
        migrations.AddField(
            model_name='analisis_riesgos',
            name='riesgo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Riesgos'),
        ),
        migrations.AddField(
            model_name='acuerdo_sla',
            name='peticion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'tipo', chained_model_field=b'peticion', on_delete=django.db.models.deletion.CASCADE, to='home.Peticion', unique=True),
        ),
        migrations.AddField(
            model_name='acuerdo_sla',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Lista_Proveedores'),
        ),
        migrations.AddField(
            model_name='acuerdo_sla',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Tipo_Peticion'),
        ),
    ]
